name: betgrid
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  firebase_core: ^2.25.4
  equatable: ^2.0.5
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.4
  injectable: ^2.3.2
  get_it:
  mocktail: ^1.0.3
  auto_route: ^7.8.4
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.0.9
  cloud_firestore: ^4.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.9
  json_serializable: ^6.7.1
  injectable_generator:
  auto_route_generator: ^7.2.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
