name: betgrid
description: "A new Flutter project."
publish_to: 'none'

version: 1.4.0+7

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  equatable: ^2.0.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  injectable: ^2.4.0
  get_it:
  mocktail: ^1.0.3
  auto_route: ^9.2.2
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.0.9
  cloud_firestore: ^5.4.3
  material_design_icons_flutter: ^7.0.7296
  rxdart: ^0.28.0
  collection: ^1.18.0
  flutter_sticky_header: ^0.6.5
  country_flags: ^3.0.0
  flutter_launcher_icons: ^0.14.1
  firebase_storage: ^12.3.2
  image_picker: ^1.0.7
  syncfusion_flutter_charts: ^27.1.51
  flutter_bloc: ^8.1.5
  bloc_test: ^9.1.7
  mutex: ^3.1.0
  cloud_functions: ^5.3.1
  betgrid_shared:
    git:
      url: https://github.com/Wojtas399/betgrid_shared.git
      ref: 079c00ecd09f1b2212d40eab7a683d712ef32f56

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.7
  json_serializable: ^6.7.1
  injectable_generator:
  auto_route_generator: ^9.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png"
  image_path_ios: "assets/ic_launcher_ios.png"
  min_sdk_android: 21
  adaptive_icon_background: "assets/ic_launcher_adaptive_back.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
