name: betgrid
description: "A new Flutter project."
publish_to: 'none'

version: 1.3.0+6

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.4
  firebase_core: ^2.25.4
  equatable: ^2.0.5
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.18.0
  injectable: ^2.3.2
  get_it:
  mocktail: ^1.0.3
  auto_route: ^8.0.2
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.0.9
  cloud_firestore: ^4.15.10
  fake_cloud_firestore: ^2.4.8
  material_design_icons_flutter: ^7.0.7296
  rxdart: ^0.27.7
  collection: ^1.18.0
  flutter_sticky_header: ^0.6.5
  country_flags: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  firebase_storage: ^11.6.11
  image_picker: ^1.0.7
  syncfusion_flutter_charts: ^24.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.9
  json_serializable: ^6.7.1
  injectable_generator:
  auto_route_generator: ^8.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png"
  image_path_ios: "assets/ic_launcher_ios.png"
  min_sdk_android: 21
  adaptive_icon_background: "assets/ic_launcher_adaptive_back.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
