include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
  exclude:
    - mason_bricks/

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_relative_imports: true
    avoid_empty_else: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    prefer_const_declarations: true
    prefer_const_constructors: true
