name: betgrid_admin
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  injectable: ^2.4.2
  mocktail: ^1.0.3
  auto_route: ^9.2.2
  flutter_bloc: ^8.1.5
  freezed_annotation: ^3.0.0
  bloc_test: ^9.1.7
  flutter_svg: ^2.0.10+1
  rxdart: ^0.28.0
  country_flags: ^3.0.0
  intl: any
  collection: ^1.18.0
  get_it: ^8.0.3
  flutter_localizations:
    sdk: flutter
  mutex: ^3.1.0
  flutter_slidable: ^3.1.2
  betgrid_shared:
    path: ../shared
  freezed: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.10
  json_serializable: ^6.7.1
  injectable_generator:
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/
